model:
  qubit:
    fQ:
      pad_gap: /Users/jagan/Codes/mqhad/models/polynomial_ridge_regression_fQ_pad_gap_in_um.pkl
      pad_height: /Users/jagan/Codes/mqhad/models/polynomial_ridge_regression_fQ_pad_height_in_um.pkl
  resonator:

target:
  qubit:
    specific:
      Q_0:
        fQ: 5.3
    general:
  resonator:
    specific:
      CU_0:
        fQ: 5.3
    general:
  